### ISSUE TITLE
Crash when restart TaskbarX

### ISSUE THREAD

**Issue by deluxghost** [ChrisAnd1998/TaskbarX#239]
I have this issue even before its name was changed to TaskbarX. **The startup task works**, but if (for some reason) TaskbarX exits, I can't launch it anymore before rebooting OS, the process just disappears simply after launching. 

I can open the configurator, but if I click stop or apply button, the configurator also crashes, and if TaskbarX is still alive, it will crashes/disappears too.

BTW, my Windows version is 1909.

Since I have this issue on old releases too, so I installed 1.5.2.0, and got this crash info when clicking stop button in the configurator:

```
System.Windows.Automation.ElementNotAvailableException: Element not available ---> System.Runtime.InteropServices.COMException: An event was unable to invoke any of the subscribers (Exception from HRESULT:0x80040201)
   at UIAutomationClient.CUIAutomation8Class.ElementFromHandleBuildCache(IntPtr hwnd, IUIAutomationCacheRequest cacheRequest)
   at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
   --- End of inner exception stack trace ---
   at System.Windows.Automation.AutomationElement.FromHandle(IntPtr hwnd)
   at TaskbarX_Configurator.Form1.ResetTaskbarStyle()
   at TaskbarX_Configurator.Form1.Button2_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

I'm not sure if it's related since there are no logs in the newest version.

**Comment by ChrisAnd1998** [comment]
@deluxghost I read your issue. Trying to understand why and where it happens.

**Comment by deluxghost** [comment]
Could you implement any log feature so I can collect and provide more info?

**Comment by ChrisAnd1998** [comment]
@deluxghost Sorry for the late response Currently there's nothing to log TaskbarX. Does it still happen with 1.5.5.0
as it now uses a different approach.

**Comment by deluxghost** [comment]
Well, since I am the only one who has this environment to replicate this bug, I decided to debug myself. I don't know VB.NET, but I found a crash case anyway, here it is.

https://github.com/ChrisAnd1998/TaskbarX/blob/1da3dd8dfcb9d676a01f5d4e82b12561676db24a/TaskbarX/TaskbarX/Main.vb#L225-L234

The problem is, not all objects have the `Name` property, I am using a custom file explorer, so I definitely have such a window. If this happens, this line will throw an exception:

https://github.com/ChrisAnd1998/TaskbarX/blob/1da3dd8dfcb9d676a01f5d4e82b12561676db24a/TaskbarX/TaskbarX/Main.vb#L229

My fix:

```vb
        Do While (i < CType(count, Integer))
            Dim item As Object = windowsType.InvokeMember("Item", BindingFlags.InvokeMethod, Nothing, windows, New Object() {i})
            Dim itemType As Type = item.GetType
            Dim itemNameInfo As PropertyInfo = itemType.GetProperty("Name")
            If (itemNameInfo <> Nothing) Then
                Dim itemName As String = CType(itemType.InvokeMember("Name", BindingFlags.GetProperty, Nothing, item, Nothing), String)
                If (itemName = "Shell_TrayWnd") Then
                    itemType.InvokeMember("Refresh", BindingFlags.InvokeMethod, Nothing, item, Nothing)
                End If
            End If
            i = (i + 1)
        Loop

```

**Comment by ChrisAnd1998** [comment]
Ohh well thats very nice you started debugging yourself. The modification still works fine on my end so i will implement it for the next update ;)
