### ISSUE TITLE
Configurator Crash during 'Apply' 

### ISSUE THREAD

**Issue by rkm0** [ChrisAnd1998/TaskbarX#290]
The TaskbarX configurator (version 1.5.5.0) crashes on my system whenever the 'Apply' button is clicked. No settings are applied either. 

> Application: TaskbarX Configurator.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at System.Diagnostics.Process.StartWithShellExecuteEx(System.Diagnostics.ProcessStartInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(System.Diagnostics.ProcessStartInfo)
   at TaskbarXConfiguratorWPF.MainWindow.RevertToZero()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

OS Build 19041.264

**Comment by ChrisAnd1998** [comment]
Does this also happen in the pre-release?
https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

**Comment by rkm0** [comment]
> @rkm0 Does this also happen in the pre-release?
> https://github.com/ChrisAnd1998/TaskbarX/releases/tag/1.5.6.0

Fixed in 1.5.6.0
