### ISSUE TITLE
When i try to install, it says missing required files: 

### ISSUE THREAD

**Issue by Cracked1l** [ChrisAnd1998/TaskbarX#842]
PLATFORM VERSION INFO
	Windows 			: 10.0.19043.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.4270.0 built by: NET48REL1LAST_C
	clr.dll 			: 4.8.4420.0 built by: NET48REL1LAST_C
	dfdll.dll 			: 4.8.4270.0 built by: NET48REL1LAST_C
	dfshim.dll 			: 10.0.19041.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///D:/TaskbarX_1.7.2.0_x86/TaskbarX.application
	Application url			: file:///D:/TaskbarX_1.7.2.0_x86/TaskbarX.exe.manifest

IDENTITIES
	Deployment Identity		: TaskbarX.application, Version=1.0.0.1, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86
	Application Identity		: TaskbarX.exe, Version=1.0.0.1, Culture=neutral, PublicKeyToken=0000000000000000, processorArchitecture=x86, type=win32

APPLICATION SUMMARY
	* Installable application.

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of D:\TaskbarX_1.7.2.0_x86\TaskbarX.application resulted in exception. Following failure messages were detected:
		+ Downloading file:///D:/TaskbarX_1.7.2.0_x86/StoreLogo-71.ico.deploy did not succeed.
		+ Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.
		+ Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.
		+ Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [11/2/2021 9:22:20 PM] : Activation of D:\TaskbarX_1.7.2.0_x86\TaskbarX.application has started.
	* [11/2/2021 9:22:20 PM] : Processing of deployment manifest has successfully completed.
	* [11/2/2021 9:22:20 PM] : Installation of the application has started.
	* [11/2/2021 9:22:20 PM] : Processing of application manifest has successfully completed.
	* [11/2/2021 9:22:25 PM] : Found compatible runtime version 4.0.30319.
	* [11/2/2021 9:22:25 PM] : Request of trust and detection of platform is complete.

ERROR DETAILS
	Following errors were detected during this operation.
	* [11/2/2021 9:22:25 PM] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file:///D:/TaskbarX_1.7.2.0_x86/StoreLogo-71.ico.deploy did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.
		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.FileNotFoundException
		- Could not find file 'D:\TaskbarX_1.7.2.0_x86\StoreLogo-71.ico.deploy'.
		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

its missing TaskbarX_1.7.2.0_x86/StoreLogo-71.ico.deploy and i cant find out how to fix

**Comment by ChrisAnd1998** [comment]
How are you installing TaskbarX? 
Go here https://chrisandriessen.nl/taskbarx
and download the recommended zip file
